# Generated by Django 6.0.4 on 2026-04-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
